version: "3.9"
services:
  web:
    build:
      context: .
      args:
        VERTICLE: MainVerticle
    environment:
      MONGO_URI: mongodb://mongo:27017
    ports:
      - "8080"
    depends_on:
      - mongo
  task:
    container_name: "task"
    build:
      context: .
      args:
        VERTICLE: TaskVerticle
    environment:
      MONGO_URI: mongodb://mongo:27017
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/for-test.json
      PROJECT_ID: for-test-304513
      BUCKET: monitor_report_monthly
    ports:
      - "8081"
    depends_on:
      - mongo
  mongo:
    container_name: "mongo"
    image: mongo
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "5000:5000"
