version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080"
    depends_on:
      - mongo
  mongo:
    container_name: "mongo"
    image: mongo
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "5000:5000"
