version: "3.9"
services:
  web:
    build:
      context: .
      args:
        VERTICLE: MainVerticle
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_URI: redis://redis:6379
    ports:
      - "8080"
    depends_on:
      - mongo
      - redis
  task:
    container_name: "task"
    build:
      context: .
      args:
        VERTICLE: TaskVerticle
    environment:
      MONGO_URI: mongodb://mongo:27017
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/for-test.json
      PROJECT_ID: for-test-304513
      BUCKET: monitor_report_monthly
    ports:
      - "8081"
    depends_on:
      - mongo
  mongo:
    container_name: "mongo"
    image: mongo
    restart: always
  lb:
    image: dockercloud/haproxy
    links:
      - web
    ports:
      - '80:80'
    environment:
      MAXCONN: 5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
